<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title><?php echo $this->escape($this->title); ?></title>
</head>
<body>
<?php
if(Zend_Auth::getInstance()->hasIdentity()) 
	{
	$session=new Zend_Session_Namespace('my_mp3');
	echo "Здравствуйте, ".$session->user;
	echo " <a href=\"/admin/\">Управление</a> ";
	echo " <a href=\"/admin/mkbd/\">Генерация БД</a> ";
	echo " <a href=\"/admin/logout/\">Выход</a> ";
	}
	else echo "<a href=\"/admin/login/\">Вход</a>";?>
    <div id="content">