<?php echo $this->render('top_a.phtml'); ?>
<?php  foreach($this->a_artist as $val)
			{
			// foreach($val as $vall) echo $this->escape($vall)."<br>";?>
<a href="<?php if($this->page==0) echo $this->escape($val[1])."\">".$this->escape($val[0]);
				else echo "/album/title/".$this->escape($val[1])."\">".$this->escape($val[0]); ?>
</a><br>

			<?php	} 
	/*else foreach($this->a_artist as $val)
			{
			// foreach($val as $vall) echo $this->escape($vall)."<br>";
			echo "<a href=\"".$this->escape($val[1])."\">".$this->escape($val[0])."</a><br>";

				} */
 ?>

<br /><br />
<div id="view-content">
	<p>View script for controller <b>Album</b> and script/action name <b>artist</b></p>
</div>
<?php echo $this->render('bottom_a.phtml'); ?>